name: deucepte_open
description: 

publish_to: 'none'

version: 4.1.1+2051

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.8
  theme_provider: ^0.5.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  background_fetch: ^1.0.1
  flutter_local_notifications: ^8.2.0
  flutter_lints: ^1.0.4
  loader_overlay: ^2.0.2
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  deu_api:
    path: packages/deu_api/
  deu_pos_api:
    path: packages/deu_pos_api/
  deu_refectory_meals_api:
    path: packages/deu_refectory_meals_api/

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.3

flutter:
  uses-material-design: true

import_sorter:
  comments: false 