name: deucepte_open
description:

publish_to: "none"

version: 4.2.0+2057

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  background_fetch: ^1.0.3
  flutter_local_notifications: ^8.2.0
  flutter_lints: ^1.0.4
  loader_overlay: ^2.0.2
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  deu_api:
    path: packages/deu_api/
  deu_pos_api:
    path: packages/deu_pos_api/
  deu_refectory_meals_api:
    path: packages/deu_refectory_meals_api/
  dynamic_color: ^1.5.4
  package_info_plus: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.3

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/logo_white.png

import_sorter:
  comments: false
